/**
 * Team name → emoji mapping for US sports leagues.
 * Used to decorate team names in game embeds.
 */

const NFL_TEAMS: Record<string, string> = {
  "Arizona Cardinals": "🔴",
  "Atlanta Falcons": "🦅",
  "Baltimore Ravens": "🟣",
  "Buffalo Bills": "🦬",
  "Carolina Panthers": "🐾",
  "Chicago Bears": "🐻",
  "Cincinnati Bengals": "🐯",
  "Cleveland Browns": "🟤",
  "Dallas Cowboys": "⭐",
  "Denver Broncos": "🐴",
  "Detroit Lions": "🦁",
  "Green Bay Packers": "🧀",
  "Houston Texans": "🤠",
  "Indianapolis Colts": "🐎",
  "Jacksonville Jaguars": "🐆",
  "Kansas City Chiefs": "🏹",
  "Las Vegas Raiders": "☠️",
  "Los Angeles Chargers": "⚡",
  "Los Angeles Rams": "🐏",
  "Miami Dolphins": "🐬",
  "Minnesota Vikings": "⚔️",
  "New England Patriots": "🗽",
  "New Orleans Saints": "⚜️",
  "New York Giants": "🗽",
  "New York Jets": "✈️",
  "Philadelphia Eagles": "🦅",
  "Pittsburgh Steelers": "⚙️",
  "San Francisco 49ers": "🏅",
  "Seattle Seahawks": "🦅",
  "Tampa Bay Buccaneers": "☠️",
  "Tennessee Titans": "⚡",
  "Washington Commanders": "🔴",
};

const NBA_TEAMS: Record<string, string> = {
  "Atlanta Hawks": "🦅",
  "Boston Celtics": "🍀",
  "Brooklyn Nets": "🕸️",
  "Charlotte Hornets": "🐝",
  "Chicago Bulls": "🐂",
  "Cleveland Cavaliers": "⚔️",
  "Dallas Mavericks": "🐴",
  "Denver Nuggets": "⛏️",
  "Detroit Pistons": "⚙️",
  "Golden State Warriors": "🌉",
  "Houston Rockets": "🚀",
  "Indiana Pacers": "🏎️",
  "Los Angeles Clippers": "⚓",
  "Los Angeles Lakers": "💜",
  "Memphis Grizzlies": "🐻",
  "Miami Heat": "🔥",
  "Milwaukee Bucks": "🦌",
  "Minnesota Timberwolves": "🐺",
  "New Orleans Pelicans": "🦤",
  "New York Knicks": "🗽",
  "Oklahoma City Thunder": "⚡",
  "Orlando Magic": "✨",
  "Philadelphia 76ers": "🔔",
  "Phoenix Suns": "☀️",
  "Portland Trail Blazers": "🔥",
  "Sacramento Kings": "👑",
  "San Antonio Spurs": "⭐",
  "Toronto Raptors": "🦖",
  "Utah Jazz": "🎵",
  "Washington Wizards": "🧙",
};

const WNBA_TEAMS: Record<string, string> = {
  "Atlanta Dream": "✨",
  "Chicago Sky": "🌤️",
  "Connecticut Sun": "☀️",
  "Dallas Wings": "🦋",
  "Indiana Fever": "🔥",
  "Las Vegas Aces": "🃏",
  "Los Angeles Sparks": "⚡",
  "Minnesota Lynx": "🐱",
  "New York Liberty": "🗽",
  "Phoenix Mercury": "⚡",
  "Seattle Storm": "⛈️",
  "Washington Mystics": "🌟",
  "Golden State Valkyries": "⚔️",
};

const MLB_TEAMS: Record<string, string> = {
  "Arizona Diamondbacks": "🐍",
  "Atlanta Braves": "🪓",
  "Baltimore Orioles": "🐦",
  "Boston Red Sox": "🧦",
  "Chicago Cubs": "🐻",
  "Chicago White Sox": "⚪",
  "Cincinnati Reds": "🔴",
  "Cleveland Guardians": "🛡️",
  "Colorado Rockies": "⛰️",
  "Detroit Tigers": "🐯",
  "Houston Astros": "🚀",
  "Kansas City Royals": "👑",
  "Los Angeles Angels": "😇",
  "Los Angeles Dodgers": "🔵",
  "Miami Marlins": "🐟",
  "Milwaukee Brewers": "🍺",
  "Minnesota Twins": "⭐",
  "New York Mets": "🌐",
  "New York Yankees": "🎩",
  "Oakland Athletics": "🐘",
  "Philadelphia Phillies": "🔔",
  "Pittsburgh Pirates": "☠️",
  "San Diego Padres": "⛪",
  "San Francisco Giants": "🌉",
  "Seattle Mariners": "⚓",
  "St. Louis Cardinals": "🐦",
  "Tampa Bay Rays": "🌊",
  "Texas Rangers": "⭐",
  "Toronto Blue Jays": "🐦",
  "Washington Nationals": "🦅",
};

const NCAAF_TEAMS: Record<string, string> = {
  "Alabama Crimson Tide": "🐘",
  "Arizona Wildcats": "🐱",
  "Arizona State Sun Devils": "😈",
  "Arkansas Razorbacks": "🐗",
  "Auburn Tigers": "🐯",
  "Baylor Bears": "🐻",
  "Boston College Eagles": "🦅",
  "BYU Cougars": "🦁",
  "California Golden Bears": "🐻",
  "Cincinnati Bearcats": "🐱",
  "Clemson Tigers": "🐯",
  "Colorado Buffaloes": "🦬",
  "Duke Blue Devils": "😈",
  "Florida Gators": "🐊",
  "Florida State Seminoles": "🪶",
  "Georgia Bulldogs": "🐶",
  "Georgia Tech Yellow Jackets": "🐝",
  "Houston Cougars": "🦁",
  "Illinois Fighting Illini": "🔴",
  "Indiana Hoosiers": "🔴",
  "Iowa Hawkeyes": "🦅",
  "Iowa State Cyclones": "🌪️",
  "Kansas Jayhawks": "🦅",
  "Kansas State Wildcats": "🐱",
  "Kentucky Wildcats": "🐱",
  "LSU Tigers": "🐯",
  "Louisville Cardinals": "🐦",
  "Maryland Terrapins": "🐢",
  "Miami Hurricanes": "🌀",
  "Michigan Wolverines": "🐺",
  "Michigan State Spartans": "⚔️",
  "Minnesota Golden Gophers": "🐿️",
  "Mississippi State Bulldogs": "🐶",
  "Missouri Tigers": "🐯",
  "Nebraska Cornhuskers": "🌽",
  "North Carolina Tar Heels": "🐏",
  "North Carolina State Wolfpack": "🐺",
  "Northwestern Wildcats": "🐱",
  "Notre Dame Fighting Irish": "☘️",
  "Ohio State Buckeyes": "🌰",
  "Oklahoma Sooners": "🏎️",
  "Oklahoma State Cowboys": "🤠",
  "Ole Miss Rebels": "🐻",
  "Oregon Ducks": "🦆",
  "Oregon State Beavers": "🦫",
  "Penn State Nittany Lions": "🦁",
  "Pittsburgh Panthers": "🐾",
  "Purdue Boilermakers": "🚂",
  "Rutgers Scarlet Knights": "⚔️",
  "South Carolina Gamecocks": "🐓",
  "Stanford Cardinal": "🌲",
  "Syracuse Orange": "🍊",
  "TCU Horned Frogs": "🐸",
  "Tennessee Volunteers": "🟠",
  "Texas Longhorns": "🤘",
  "Texas A&M Aggies": "🐕",
  "Texas Tech Red Raiders": "🔴",
  "UCLA Bruins": "🐻",
  "USC Trojans": "⚔️",
  "Utah Utes": "🔴",
  "Vanderbilt Commodores": "⚓",
  "Virginia Cavaliers": "⚔️",
  "Virginia Tech Hokies": "🦃",
  "Wake Forest Demon Deacons": "😈",
  "Washington Huskies": "🐺",
  "Washington State Cougars": "🦁",
  "West Virginia Mountaineers": "⛰️",
  "Wisconsin Badgers": "🦡",
};

const NCAAB_TEAMS: Record<string, string> = {
  "Alabama Crimson Tide": "🐘",
  "Arizona Wildcats": "🐱",
  "Arkansas Razorbacks": "🐗",
  "Auburn Tigers": "🐯",
  "Baylor Bears": "🐻",
  "Cincinnati Bearcats": "🐱",
  "Clemson Tigers": "🐯",
  "Colorado Buffaloes": "🦬",
  "Connecticut Huskies": "🐺",
  "Creighton Bluejays": "🐦",
  "Duke Blue Devils": "😈",
  "Florida Gators": "🐊",
  "Florida State Seminoles": "🪶",
  "Gonzaga Bulldogs": "🐶",
  "Georgia Bulldogs": "🐶",
  "Houston Cougars": "🦁",
  "Illinois Fighting Illini": "🔴",
  "Indiana Hoosiers": "🔴",
  "Iowa Hawkeyes": "🦅",
  "Iowa State Cyclones": "🌪️",
  "Kansas Jayhawks": "🦅",
  "Kansas State Wildcats": "🐱",
  "Kentucky Wildcats": "🐱",
  "Louisville Cardinals": "🐦",
  "LSU Tigers": "🐯",
  "Marquette Golden Eagles": "🦅",
  "Maryland Terrapins": "🐢",
  "Memphis Tigers": "🐯",
  "Miami Hurricanes": "🌀",
  "Michigan Wolverines": "🐺",
  "Michigan State Spartans": "⚔️",
  "North Carolina Tar Heels": "🐏",
  "Notre Dame Fighting Irish": "☘️",
  "Ohio State Buckeyes": "🌰",
  "Oklahoma Sooners": "🏎️",
  "Oregon Ducks": "🦆",
  "Penn State Nittany Lions": "🦁",
  "Purdue Boilermakers": "🚂",
  "Rutgers Scarlet Knights": "⚔️",
  "San Diego State Aztecs": "⚔️",
  "St. John's Red Storm": "🌩️",
  "Syracuse Orange": "🍊",
  "Tennessee Volunteers": "🟠",
  "Texas Longhorns": "🤘",
  "Texas A&M Aggies": "🐕",
  "Texas Tech Red Raiders": "🔴",
  "UCLA Bruins": "🐻",
  "USC Trojans": "⚔️",
  "Villanova Wildcats": "🐱",
  "Virginia Cavaliers": "⚔️",
  "West Virginia Mountaineers": "⛰️",
  "Wisconsin Badgers": "🦡",
  "Xavier Musketeers": "🎯",
};

const ALL_TEAMS: Record<string, string> = {
  ...NFL_TEAMS,
  ...NBA_TEAMS,
  ...WNBA_TEAMS,
  ...MLB_TEAMS,
  ...NCAAF_TEAMS,
  ...NCAAB_TEAMS,
};

/**
 * Returns the emoji for a team name, or an empty string if not found.
 */
export function getTeamEmoji(teamName: string): string {
  if (ALL_TEAMS[teamName]) return ALL_TEAMS[teamName];

  const lower = teamName.toLowerCase();
  for (const [key, emoji] of Object.entries(ALL_TEAMS)) {
    if (key.toLowerCase() === lower) return emoji;
  }

  return "";
}

/**
 * Decorates a team name with its emoji, e.g. "🏹 Kansas City Chiefs"
 */
export function withTeamEmoji(teamName: string): string {
  const emoji = getTeamEmoji(teamName);
  return emoji ? `${emoji} ${teamName}` : teamName;
}
